services:
  db-quiz-app:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Start123!
      POSTGRES_DB: default_database
    volumes:
      - ./db-data/:/var/lib/postgresql/

  auth:
    build:
      context: ./backend/
      dockerfile: ./crates/auth-service/dockerfile
    environment:
      DATABASE_URL: postgres://admin:Start123!@db-quiz-app:5432/quiz-auth
      JWT_SECRET: dev-only-secret
    ports:
      - "3000:3000"
    depends_on:
      - db-quiz-app

  quiz-service:
    build:
      context: ./backend/
      dockerfile: ./crates/quiz-service/dockerfile
    environment:
      DATABASE_URL: postgres://admin:Start123!@db-quiz-app:5432/quiz-service-db
      CRON_JOB: "0 0 * * * *"
      ADDRESS: "0.0.0.0:3000"
    ports:
      - "4000:3000"
    depends_on:
      - db-quiz-app

volumes:
  pgdata:
