# ---- build stage ----
FROM rust:1.94 AS builder
WORKDIR /app

COPY . .

RUN cargo build --release -p auth-service

# ---- runtime stage ----
FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/auth-service /app/auth-service

EXPOSE 3000
CMD ["./auth-service"]
