FROM rust:1.94 AS builder
WORKDIR /app

COPY . .

RUN cargo build --release -p quiz-service

# ---- runtime stage ----
FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/quiz-service /app/quiz-service

EXPOSE 3000
CMD ["./quiz-service"]
